services:
  - type: web
    name: edusecure-backend
    env: docker
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: RENDER_DISK_PATH
        value: /var/data
    disk:
      name: models_cache
      mountPath: /var/data
      sizeGB: 1
